### ISSUE TITLE
Accessing the CN of a certificate

### ISSUE THREAD

**Issue by kpcyrd** [rusticata/x509-parser#50] opened 2020-10-02 21:37 UTC
hello!

There are some changes in the latest release that are related to the common name of the certificate, is there an intended way to access the CN, that's less low-level than the current approach?

Thanks!

**Comment by chifflier** [comment] 2020-10-05 15:23
Hi,
I suppose you are taking of the Subject. It is a `X509Name`, and implements for high-level the `Display` trait (and so, the `to_string()` method) if you want a quick formatting of the result.
Is that what you are looking for, or do you want to access some specific part? I can add methods for the most common use cases.

**Comment by kpcyrd** [comment] 2020-10-06 01:16
I want to access a specific part :) CN= is the part I'm interested in (sorry in case that wasn't clear)

For the given cert:
```
-----BEGIN CERTIFICATE-----
MIIE5zCCA8+gAwIBAgIQBvsKfZ5AGSW3Vc8Ldto1hTANBgkqhkiG9w0BAQUFADBp
MSQwIgYJKoZIhvcNAQkBFhVwa2lfYWRtaW5Ac3VuZ2FyZC5jb20xJjAkBgNVBAoT
HVN1bkdhcmQgQXZhaWxhYmlsaXR5IFNlcnZpY2VzMRkwFwYDVQQDExBTQVMgUHVi
bGljIENBIHYxMB4XDTEwMDkwMjE2MzY0OVoXDTExMTAwMTE2MzEwMFowgbQxCzAJ
BgNVBAYTAlVTMQswCQYDVQQIEwJPUjERMA8GA1UEBxMIUG9ydGxhbmQxEzARBgoJ
kiaJk/IsZAEZFgNjb20xHDAaBgoJkiaJk/IsZAEZFgxqaXZlc29mdHdhcmUxHDAa
BgNVBAoTE0ppdmUgU29mdHdhcmUsIEluYy4xEDAOBgNVBAsTB0hvc3RpbmcxIjAg
BgNVBAMTGSouaG9zdGVkLmppdmVzb2Z0d2FyZS5jb20wggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQC0oornTIyL5YjZMpNwy+V2YJbLqaLrbPrbWFCsNJDx
dnubjfR71aW+YYlUZF8zoq4jFetkblCehyvPEb5tD/l3/WZhiXYOziPDrsEVCngF
3/b0H3Dyk6mNWBZcNpJkdpOx1YB6Zer8eKzFOr7Qj3aevOR/bEe2NARJIaO0Rjwe
YIWY0arKRm6z4nJD8fYAvFV6wRWmHsZO9ci7hiGeW3YL6jQYJqLeuwXm64l0jptb
Qg8r8c1V5BXETlvQJL34gUozEl9jDpzR7KoXtErhlU2ytl9Wg+fOxYuWgx8vER0/
7Hqc/qD5e7B+NtwgfEio7SvNGA/HhjNxW2Wbrx4qooJRAgMBAAGjggE9MIIBOTAO
BgNVHQ8BAf8EBAMCA6gwEQYJYIZIAYb4QgEBBAQDAgbAMCIGA1UdEQQbMBmBF3N1
YmplY3RuYW1lQGV4YW1wbGUuY29tMB8GA1UdIwQYMBaAFDhBxvKFgYP96+IaNpI7
JmEWgRESMFQGA1UdIARNMEswSQYJKoZIhvcNBQYBMDwwOgYIKwYBBQUHAgEWLmh0
dHBzOi8vY2VydGlmaWNhdGUuc3VuZ2FyZC5jb20vU0FTX0NBX0NQUy5wZGYwRQYD
VR0fBD4wPDA6oDigNoY0aHR0cHM6Ly9jZXJ0aWZpY2F0ZS5zdW5nYXJkLmNvbS9T
QVNfUHVibGljX0NBX3YxLmNybDATBgNVHSUEDDAKBggrBgEFBQcDATAdBgNVHQ4E
FgQUhJ99py6oeCYBzcePPjhOxHVDBvwwDQYJKoZIhvcNAQEFBQADggEBAF/DAJgX
f50x8t8Im96AUn4DqC+T0QZIYHihpj2uCwWDbdp5efppqTrk6FrpFOzQy0TRkstb
Q3zKSgduedQiwii9qh88O1h2gbSTqfi55ApOIGoCiiRCqio2p4tbKyqPV3Q0eyYw
K4f9GAOcawvNsI//mx99ol/ZGEamydeL9G0qiKrhqSxd2TGmFaIVJdu9fh59hos4
6t9c4FVyYygdsIeGHkHjpB2bKjZhnJpKRh9dGWctcjdHMITBBqgiRH9OZa/w6SPE
UT+11L6q7MSIXSIMV8kJSUUYE92P7bnAqViTIuu/hHnfmIhiy6t7AuT2QHEhqDab
EF4l5MwdUqs8FvM=
-----END CERTIFICATE-----
```
The value I'm trying to get is:
```
*.hosted.jivesoftware.com
```

**Comment by chifflier** [comment] 2020-10-06 07:56
Hum, you're right, to do that right now you'll need to access the subject, filter on CN OID, and get the value.
That makes too many operations, so I'll add an API to do that.

**Comment by chifflier** [comment] 2020-10-06 12:58
An API has been added in 92fa04d and will be released in 0.8.1 (non-breaking, only added methods).
It brings the ability to access an attribute of `X509Name` (for ex. the CN), but there is some complexity (due to the X.509 specification): attributes can be present multiple times, they can be encoded as binary (instead of strings), etc.
I tried to simplify that as much as possible, while preserving the ability to access all fields.
Feedback welcome!

**Closed by chifflier** 2020-10-06 12:58 UTC

**Comment by kpcyrd** [comment] 2020-10-06 13:31
Thanks! The new api is very neat, unfortunately it doesn't work for the certificate I've attached. The `Display` representation of the subject is:
```
C=US, ST=OR, L=Portland, OID(0.9.2342.19200300.100.1.25)=com, OID(0.9.2342.19200300.100.1.25)=jivesoftware, O=Jive Software, Inc., OU=Hosting
```
I'm wondering if this is related. openssl is decoding the subject as:
```
Subject: C = US, ST = OR, L = Portland, DC = com, DC = jivesoftware, O = "Jive Software, Inc.", OU = Hosting, CN = *.hosted.jivesoftware.com
```

**Comment by chifflier** [comment] 2020-10-06 14:10
For what I see, the OID for domainComponent (DC) is not known, so it is left to displaying the OID.
I'll add it to the database of known OIDs.

That said, something else puzzles me: the second CN (with the wildcard) is not displayed. That may be something else - I'll investigate.

If those problems are confirmed, I'll open separate issues.

Thanks!

**Comment by chifflier** [comment] 2020-10-06 14:35
Heh, the debugging session was "interesting".

For problem number 2 (wildcard not parsed):
The culprit is in `der_parser`, precisely when attempting to parse the DER object from the certificate. Object is declared as PrintableString, and the content is "*.hosted.jivesoftware.com". However, this is invalid according to [PrintableString specification](https://en.wikipedia.org/wiki/PrintableString):

> The PrintableString definition does not include asterisk (*) which means it must not be used to represent a wildcard in an X.509 digital certificate Distinguished Name.

So the TL;DR is the certificate is not valid DER encoding. However, it would be interesting to be able to parse it anyway. I'll think of a way to handle this correctly (opening an issue on `der-parser`).

**Comment by kpcyrd** [comment] 2020-10-07 16:46
I've tested the x509-parser-0.8 branch again with the new commit and it's working now! Thanks! :heart:
